import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/MediaList.module.css'
import RoundedDiv from '@/components/RoundedDiv'
import BlurPanel from '@/components/BlurPanel'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>8. Mai 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.container}>
      
        <h2>Fotograf: Lars Kristian Småge Syvertsen</h2>
        <div className={styles.links}>
        <div className={styles.row}>
          <Link href={"/projects/08052023#bekk"} >Bekk</Link>  
          <Link href={"/projects/08052023#arkitektur"} >Arkitektur</Link>  
          <Link href={"/projects/08052023#monumentet"} >Monumentet</Link>  
          <Link href={"/projects/08052023#ender"} >Ender</Link>  
        </div> 
      </div>
      <div className={styles.main}>
          <section id="bekk" className={styles.section}>

            <img src={`/images/FlytendeBekk.jpg`} alt="Flytende Bekk" /> 

            <div>
              <h2>Flytende bekk</h2>
              <div className={styles.row}>
                <p>4&quot; Lukkertid</p>
                <p>36 Blender</p>
                <p>100 ISO</p>
              </div>
              <p>Redigert i photoshop, eksponering og fjernet flekker.</p>
              <a href='https://goo.gl/maps/noDCYGkD3tYv1JYS9'>Google Maps</a>
            </div>
          </section>

          <section id="arkitektur" className={styles.section}>

            <img src={`/images/DSC_0318.JPG`} alt="Flytende Bekk" /> 

            <div>
              <h2>Klostergahen 39</h2>
              <div className={styles.row}>
                <p>1/160 Lukkertid</p>
                <p>8 Blender</p>
                <p>100 ISO</p>
              </div>
              <p>Arkitektur, Havfruen blokkerer solen og skaper en skimrende effekt. Vinkelen får bygningen til å se større ut.</p>
              <a href='https://goo.gl/maps/FTHCxWzyVx1mkNuq8'>Google Maps</a>
            </div>
          </section>
          
          <section id={"monumentet"}  className={styles.section}>

            <img src={`/images/MettalGutter.JPG`} alt="Monument" /> 

            <div>
              <h2>Fløtermonumentet</h2>
              <div className={styles.row}>
                <p>1/160 Lukkertid</p>
                <p>8 Blender</p>
                <p>100 ISO</p>
              </div>
              <p></p>
              <a href='https://goo.gl/maps/CD1PqeqVrnsDvD1g6'>Google Maps</a>
            </div>
          </section>

          <section id={"ender"} className={styles.section}>

            <img src={`/images/DuckFly.JPG`} alt="Ender" /> 

            <div>
              <h2>Ender</h2>
              <div className={styles.row}>
                <p>1/640 Lukkertid</p>
                <p>5.6 Blender</p>
                <p>800 ISO</p>
              </div>
              <p>Redigert i photoshop, eksponering og fjernet flekker.</p>
              <a href='https://goo.gl/maps/P1JEJRbTfVCT1Etu5'>Google Maps</a>
            </div>
          </section>
      </div>
      

      
        

    
      </div>
    </>
  )
}
