import Head from "next/head";
import Link from "next/link";

export default function({children}) {
    return (
        <div>
                  <Head>
                    <title>Grayr - 2.0</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                  </Head>
                  
                  <nav>
                      <Link href={"/"}>Home</Link>
                      <Link href={"/upload"}>Upload</Link>
                  </nav>

                  <main>
                    {children}
                  </main>
        </div>
    );
}