import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/layouts/FileSharingLayout.module.css"
import { useState } from "react";
import LoginButton from "@/components/LoginButton"
import Image from "next/image";
import { Badge, ColorImage } from "@/components";
import useFetch from "@/hooks/useFetch";  
import { GetShortHandle } from "@/lib/ShorthandHelper";
import { useRouter } from "next/router";
import { isSourceContentType } from "@/lib/ExtensionHelper";

export default function Layout({children, pageId = 0, batches}) {
    const router = useRouter()
    const [current, setCurrent] = useState(pageId)

    return (
        <div>
                  <Head>
                    <title>Aktuelt.tv Dashboard</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/aktueltstudio_logo.svg" />
                  </Head>
                  
                  <nav className={styles.nav}>
                      <Link className={current === -1 ? styles.element : styles.default} href={"/"}><Image width={30} height={30} src={"/aktueltstudio_logo.svg"} /></Link>
                      {/* <Link className={current === 0 ? styles.element : styles.default} href={"/dashboard"}>files</Link> */}
                      <Link className={current === 2 ? styles.element : styles.default} href={"/dashboard/batches"}>Batches</Link>
                      <Link className={current === 3 ? styles.element : styles.default} href={"/dashboard/articles"}>Articles</Link>
                      <Link className={current === 4 ? styles.element : styles.default} href={"/dashboard/series"}>Series</Link>
                      <LoginButton />
                  </nav>
                  
                  <nav className={styles.actionBar}>
                    {batches && batches.map((batch) =>
                      <Badge style={{cursor: "pointer", overflow: "hidden"}} key={batch.id} onClick={() => router.push("/dashboard/batches/" + batch.id)}>
                            {batch.thumbnail && isSourceContentType(batch.thumbnail, "image") && <ColorImage style={{zIndex: 0}} source={batch.thumbnail} /> }
                            <h2 style={{zIndex: 1}}>{GetShortHandle(batch.title).combined}</h2>
                      </Badge>
                    )}
                  </nav>

                  <main className={styles.main}>
                    {children}
                  </main>
        </div>
    );

    
}