import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/layouts/FileSharingLayout.module.css"
import { useState } from "react";

export default function Layout({children, pageId = 0}) {

  const [current, setCurrent] = useState(pageId)

    return (
        <div>
                  <Head>
                    <title>Grayr - 2.0</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                  </Head>
                  
                  <nav className={styles.nav}>
                      <Link className={current === 0 ? styles.element : styles.default} href={"/"}>Home</Link>
                      <Link className={current === 1 ? styles.element : styles.default} href={"/upload"}>Upload</Link>
                      <Link className={current === 2 ? styles.element : styles.default} href={"/batches"}>Batches</Link>
                  </nav>

                  <main>
                    {children}
                  </main>
        </div>
    );
}