import Head from "next/head";
import Link from "next/link";
import styles from "@/styles/layouts/FileSharingLayout.module.css"
import { useState } from "react";
import LoginButton from "@/components/LoginButton"

export default function Layout({children, pageId = 0}) {

  const [current, setCurrent] = useState(pageId)

    return (
        <div>
                  <Head>
                    <title>Aktuelt.tv - Filer</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/aktueltstudio_logo.svg" />
                  </Head>
                  
                  <nav className={styles.nav}>
                      <Link className={current === -1 ? styles.element : styles.default} href={"/"}>Home</Link>
                      <Link className={current === 0 ? styles.element : styles.default} href={"/dashboard"}>files</Link>
                      <Link className={current === 2 ? styles.element : styles.default} href={"/batches"}>Batches</Link>
                      <LoginButton />
                  </nav>

                  <main className={styles.main}>
                    {children}
                  </main>
        </div>
    );
}