import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import RoundedDiv from '@/components/RoundedDiv'

const inter = Inter({ subsets: ['latin'] })

const items = [
  {banner: 'https://images.pexels.com/photos/4100769/pexels-photo-4100769.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'},
  {banner: 'https://images.pexels.com/photos/4237062/pexels-photo-4237062.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'},
  {title: "Contestants needed!", banner: 'https://i.gyazo.com/a8d5f03b0f5e9f7eb080fa27983e380c.png'},
  {banner: 'https://images.pexels.com/photos/6954162/pexels-photo-6954162.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'},
  {banner: 'https://images.pexels.com/photos/5745057/pexels-photo-5745057.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'}
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.container}>
      <div className={styles.grid}>
        

        <div className={styles.work}>
          <h2>Nyeste Oppdrag</h2>
          <div className={styles.workGrid}>
            {items.map((item, index) => {

              return (
                <div key={index} className={styles['item' + parseFloat(index + 1)]} style={{backgroundImage: `url(${item.banner})`}}>
                  <div className={styles.workDetail}>
                    <p>{item.title ? item.title : "Oppgave " + (index + 1)}</p>
                    <div>
                      <img src={item.banner} className={styles.avatar} />
                      <p>1MEA</p>
                    </div>
                    <div className={styles.workOptions}>
                      <p>Redigering</p>
                      <p>Foto</p>
                    </div>
                  </div>
                </div>
              )
            
            })}

          </div>
        </div>

        <div className={styles.right}>
          CUM
        </div>
        

    </div>
      </div>


    </>
  )
}
